apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: huqy23f74-java-springboot
  janus-idp.io/tekton: huqy23f74-java-springboot
  backstage.io/kubernetes-id: huqy23f74-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: huqy23f74-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
